---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      # check file format
      - name: check json
        id: check-json
      - name: check yaml
        id: check-yaml
      # check misc
      - name: check added large files
        id: check-added-large-files
      - name: check executables with shebangs
        id: check-executables-have-shebangs
      - name: check shebangs scripts are executable
        id: check-shebang-scripts-are-executable
        exclude: .py$
      # update content
      - name: update end of file without newline
        id: end-of-file-fixer
        exclude: ^dist/
      - name: update to trim whitespace from ends of lines
        id: trailing-whitespace
        exclude: ^dist/
      - name: update to sort requirements.txt
        id: requirements-txt-fixer
      # security
      - name: detect aws credentials
        id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - name: detect private key
        id: detect-private-key

  # Check Files and Configurations
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.36.2"
    hooks:
      - name: validate yaml lint
        id: yamllint
        args:
          [
            "-c",
            ".github/workflows/config/yamllint-cfg.yaml"
          ]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.26"
    hooks:
      - name: terraform-fmt
        id: terraform-fmt
      - name: terraform-lint
        id: tflint
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.2.386"
    hooks:
      - name: scan IaC
        id: checkov
        args:
          [
            "--skip-results-upload",
            "--enable-secret-scan-all-files",
            "--skip-check", "CKV_GIT_1",
            "--skip-check", "CKV_GIT_3",
            "--skip-check", "CKV_GIT_5",
            "--skip-check", "CKV2_GIT_1",
            "--skip-check", "CKV2_GHA_1",
            "--skip-check", "CKV_DOCKER_2",
            "--skip-check", "CKV_DOCKER_3",
          ]

  # Check Github Action
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.31.3"
    hooks:
      - name: check github actions workflows
        id: check-github-workflows
        args: ["--verbose"]
#
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: "v4.0.0-alpha.8"
#    hooks:
#      - id: prettier
#  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: v0.1.0
#    hooks:
#      - id: dockerfilelint
