repos:
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.32.1
  hooks:
  - name: Check GitHub Actions Workflows
    id: check-github-workflows
    args:
    - --verbose
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
  - name: Check Dockerfile
    id: hadolint
    args:
    - --config
    - .github/config/hadolint-cfg.yaml
- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.0
  hooks:
  - name: Check Yaml
    id: yamllint
    args:
    - --no-warnings
    - -c=.github/config/yamllint-cfg.yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - name: Check JSON
    id: check-json
    types:
    - json
  - name: Check added large files
    id: check-added-large-files
    args:
    - --maxkb=2000
  - name: Check executables with shebangs
    id: check-executables-have-shebangs
  - name: Check shebangs scripts are executable
    id: check-shebang-scripts-are-executable
    exclude: .py$
  - name: Fix newline at end of file
    id: end-of-file-fixer
    exclude: ^tests/
  - name: Fix to trim whitespace from ends of lines
    id: trailing-whitespace
    exclude: ^tests/
  - name: Python sort requirements.txt
    id: requirements-txt-fixer
  - name: Python check files parse as valid python
    id: check-ast
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - name: Python isort
    id: isort
- repo: https://github.com/pycqa/flake8
  rev: 7.2.0
  hooks:
  - name: Python flake8
    id: flake8
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.98.0
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_validate
- repo: https://github.com/bridgecrewio/checkov
  rev: 3.2.394
  hooks:
  - name: Checkov Scan
    id: checkov
    files: \.tf$|\.tfvars$|\.json$|\.y(a)?ml$|\.py$|\.sh$|\.md$
    args:
    - --skip-results-upload
    - --enable-secret-scan-all-files
    - --skip-check
    - CKV_GIT_1
    - --skip-check
    - CKV_GIT_3
    - --skip-check
    - CKV_GIT_5
    - --skip-check
    - CKV2_GIT_1
    - --skip-check
    - CKV2_GHA_1
    - --skip-check
    - CKV_DOCKER_2
    - --skip-check
    - CKV_DOCKER_3
    - --quiet
