---
repos:
  ## Check and Flag Issues with Configurations, Files, Format
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.31.3"
    hooks:
      - name: Check GitHub Actions Workflows
        id: check-github-workflows
        args: ["--verbose"]
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.36.2"
    hooks:
      - name: Check yaml
        id: yamllint
        args:
          [--strict, -c=.github/workflows/config/yamllint-cfg.yaml]
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.12.0"
    hooks:
      - name: Check Dockerfile
        id: hadolint
        args: [--config, .github/workflows/config/hadolint-cfg.yaml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - name: Check json
        id: check-json
      - name: Check added large files
        id: check-added-large-files
      - name: Check executables with shebangs
        id: check-executables-have-shebangs
      - name: Check shebangs scripts are executable
        id: check-shebang-scripts-are-executable
        exclude: .py$
      - name: Fix end of file without newline
        id: end-of-file-fixer
        exclude: ^test/
      - name: Fix to trim whitespace from ends of lines
        id: trailing-whitespace
        exclude: ^test/
      - name: Fix to sort requirements.txt
        id: requirements-txt-fixer
      - name: Detect aws credentials
        id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - name: Detect private key
        id: detect-private-key

  ## Terraform
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: "v0.1.26"
    hooks:
      - name: Terraform format
        id: terraform-fmt
      - name: Terraform linter
        id: tflint

  ## Scan IaC
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "3.2.386"
    hooks:
      - name: Checkov scan IaC
        id: checkov
        files: \.tf$|\.tfvars$|\.json$|\.y(a)?ml$|\.py$|\.sh$|\.md$
        args:
          [
            "--skip-results-upload",
            "--enable-secret-scan-all-files",
            "--skip-check", "CKV_GIT_1",
            "--skip-check", "CKV_GIT_3",
            "--skip-check", "CKV_GIT_5",
            "--skip-check", "CKV2_GIT_1",
            "--skip-check", "CKV2_GHA_1",
            "--skip-check", "CKV_DOCKER_2",
            "--skip-check", "CKV_DOCKER_3",
            "--quiet"
          ]
#
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: "v4.0.0-alpha.8"
#    hooks:
#      - id: prettier
#  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: v0.1.0
#    hooks:
#      - id: dockerfilelint
