---
# NOTE: this file is managed through terraform
# ref: https://github.com/marketplace/actions/yaml-lint

extends: default

rules:
  line-length:
    max: 110
    level: warning

  indentation: disable
