name: Run Script on Schedule

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: pre-commit setup
        run: |
          pre-commit install
          pre-commit --version

      - name: pre-commit run everything
        run: |
          pre-commit run -a

      - name: Make Script Executable
        run: chmod +x update.py

      # - name: Run Script
      #   run: update.py
