name: Scheduled-Run Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install hadolint
        run: echo $PATH

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install general dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip --version

      - name: Install hadolint
        run: >-
          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x hadolint
          sudo mv hadolint /bin/

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2"

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.55.1

      - name: pre-commit setup
        run: |
          pre-commit install
          pre-commit --version

      - name: pre-commit run everything
        run: |
          pre-commit run -a

      - name: Make Script Executable
        run: chmod +x update.py

      # - name: Run Script
      #   run: update.py
