name: cron-coverage

on:
  schedule:
    - cron: '15 22 * * 0'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.x'

permissions:
  contents: write
  pull-requests: write

jobs:
  coverage-test:
    runs-on: ubuntu-latest

    outputs:
      COV_PER: ${{ steps.get-coverage-results.outputs.COV_PER }}
      COV_RUN: ${{ steps.get-coverage-results.outputs.COV_RUN }}
      COV_REP: ${{ steps.get-coverage-reports.outputs.COV_REP }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install python dependencies
      run: |
        pip install -e .
        pip --version
        pip install coverage[toml]

    - id: run-coverage-tests
      run: |
        coverage run tests/test_run.py -v
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: "1"

    - id: export-coverage
      run: |
        coverage html
        coverage report
      env:
        PYTHONUNBUFFERED: "1"

    - id: get-coverage-results
      run: |
        echo "COV_RUN=${{ steps.run-coverage-tests.outcome }}"            >> "$GITHUB_OUTPUT"
        echo "COV_PER=$(coverage report | grep TOTAL | awk '{print $6}')" >> "$GITHUB_OUTPUT"
        echo "COV_REP=$(cat htmlcov/index.html)"                          >> "$GITHUB_OUTPUT"

  notify-slack:
    if: always()
    needs: [coverage-test]

    runs-on: ubuntu-latest

    steps:

    - name: Post coverage result to Slack
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "*Repository : ${{ github.repository }}*\n*Workflow   : ${{ github.workflow }}*
            ```
            Coverage Tests     : ${{ needs.coverage-test.outputs.COV_RUN }}\n
            Coverage Percentage: ${{ needs.coverage-test.outputs.COV_PER }}\n
            Workflow URL       : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ```"

    - name: Post coverage report to Slack
      uses: slackapi/slack-github-action@v2
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          attachments: "${{ needs.coverage-test.outputs.COV_REP }}"
