name: cron-update-pre-commit

on:
  schedule:
    - cron: '15 22 * * 6'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.x'

permissions:
  contents: read

jobs:
  update-hooks:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    outputs:
      OUTCOME: ${{ steps.run-update-pre-commit.outcome }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -e .
        python -m pip --version

    - id: run-update-pre-commit
      run: python src/update_pre_commit/run.py --dry-run false
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: "1"

  notify-slack:
    if: always()
    needs: [update-hooks]

    runs-on: ubuntu-latest

    steps:

    - name: Post message to Slack
      uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "*Repository : ${{ github.repository }}*\n*Workflow   : ${{ github.workflow }}*
            ```
            Run Result  : ${{ needs.update-hooks.outputs.OUTCOME }}\n
            Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ```"
