name: cron-update-pre-commit

on:
  schedule:
    - cron: '15 22 * * 6'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13.2'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-hooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install python dependencies
        run: |
          pip install -e .
          pip --version

      - name: Update pre-commit hooks and create PR
        run: python update_pre_commit/run.py --dry-run false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1"
