name: Licensed

on:
  workflow_call:

jobs:
  validate-cached-dependency-records:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install licensed tool
        run: |
          cd "$RUNNER_TEMP"
          curl -Lfs -o licensed.tar.gz https://github.com/github/licensed/releases/download/3.9.1/licensed-3.9.1-linux-x64.tar.gz
          sudo tar -xzf licensed.tar.gz
          sudo mv licensed /usr/local/bin/licensed

      - name: update the metadata cache and create the missing metadata file
        run: licensed cache

      - name: Check cached dependency records
        run: licensed status
