---
name: Terraform-Linter
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - test-*
  pull_request:
    branches:
      - main

jobs:
  tflint:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Create Cache plugin dir
      run: mkdir -p ~/.tflint.d/plugins
    - name: Cache plugin dir
      uses: actions/cache@v4
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.55.1
    - name: Show version
      run: tflint --version
    - name: Init TFLint
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        # Summary: TFLint calls the GitHub API to get release metadata
        GITHUB_TOKEN: ${{ github.token }}
    - name: Run TFLint
      run: tflint --recursive -f json
