---
name: Terraform-Validate
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - test-*
  pull_request:
    branches:
      - main

jobs:
  tfvalidate:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: terraform validate
        id: validate
        uses: dflook/terraform-validate@v1
        # with:
        #   path: my-terraform-config
