---
name: Track PyPI Version
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - test-*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  track-pypi-version:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Check requirements.txt
        uses: Verbalinsurection/track-pypi-version@1.1.6
        id: checkr
        with:
          compush: "true"
          backup: "true"
          reqfile: "./requirements.txt"
      - name: Get if update needed output
        run: echo ${{ steps.checkr.outputs.commit }}
